### PR TITLE
refactor stuff, enforce DRY(I actually tested!)

### PR DESCRIPTION
**Pull request by justchen1369**

### CODE REVIEW

**Comment by ghost** [comment]
Just curious, but can you show that everything is infact, still working?

**Comment by justchen1369** [comment]
I can run the express server(server.js) and everything works fine, including creating a new username, logging in, logging out, and switching modes.

**Comment by ghost** [comment]
Setting panels and all toggles still fine?

**Comment by justchen1369** [comment]
I only changed leaderboard.js and levelgen.js, but yes, everything is working fine.

**Comment by ghost** [comment]
I was just asking because based on past experiences, as soon as one thing stops working, the entire game just commits no. I'll merge then I guess.

**Comment by justchen1369** [comment]
now let's see if anything broke.(highly unlikely)

**Comment by ghost** [comment]
Good thing the revert button is still there.

**Pull request merged**
